# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detector_create <- function(family, info, theta0 = NULL, dim_indexes = NULL, pruning_mult = 2L, pruning_offset = 1L, side = "right") {
    .Call(`_focus_detector_create`, family, info, theta0, dim_indexes, pruning_mult, pruning_offset, side)
}

detector_update <- function(detector_ptr, y) {
    invisible(.Call(`_focus_detector_update`, detector_ptr, y))
}

detector_statistic <- function(detector_ptr) {
    .Call(`_focus_detector_statistic`, detector_ptr)
}

detector_changepoint <- function(detector_ptr) {
    .Call(`_focus_detector_changepoint`, detector_ptr)
}

detector_pieces_len <- function(detector_ptr) {
    .Call(`_focus_detector_pieces_len`, detector_ptr)
}

detector_info_n <- function(detector_ptr) {
    .Call(`_focus_detector_info_n`, detector_ptr)
}

detector_info_sn <- function(detector_ptr) {
    .Call(`_focus_detector_info_sn`, detector_ptr)
}

detector_candidates <- function(detector_ptr) {
    .Call(`_focus_detector_candidates`, detector_ptr)
}

rcpp_hello_world <- function() {
    .Call(`_focus_rcpp_hello_world`)
}

