# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detector_create <- function(family, info) {
    .Call(`_focus_detector_create`, family, info)
}

detector_update <- function(detector_ptr, y) {
    invisible(.Call(`_focus_detector_update`, detector_ptr, y))
}

detector_statistic <- function(detector_ptr) {
    .Call(`_focus_detector_statistic`, detector_ptr)
}

detector_changepoint <- function(detector_ptr) {
    .Call(`_focus_detector_changepoint`, detector_ptr)
}

detector_pieces_len <- function(detector_ptr) {
    .Call(`_focus_detector_pieces_len`, detector_ptr)
}

detector_info_n <- function(detector_ptr) {
    .Call(`_focus_detector_info_n`, detector_ptr)
}

detector_info_sn <- function(detector_ptr) {
    .Call(`_focus_detector_info_sn`, detector_ptr)
}

rcpp_hello_world <- function() {
    .Call(`_focus_rcpp_hello_world`)
}

