# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detector_create <- function(type, theta0 = NULL, dim_indexes = NULL, pruning_mult = 2L, pruning_offset = 1L, side = "right") {
    .Call(`_focus_detector_create`, type, theta0, dim_indexes, pruning_mult, pruning_offset, side)
}

detector_update <- function(info_ptr, y) {
    invisible(.Call(`_focus_detector_update`, info_ptr, y))
}

get_statistics <- function(info_ptr, family, theta0 = NULL) {
    .Call(`_focus_get_statistics`, info_ptr, family, theta0)
}

detector_pieces_len <- function(info_ptr) {
    .Call(`_focus_detector_pieces_len`, info_ptr)
}

detector_info_n <- function(info_ptr) {
    .Call(`_focus_detector_info_n`, info_ptr)
}

detector_info_sn <- function(info_ptr) {
    .Call(`_focus_detector_info_sn`, info_ptr)
}

detector_candidates <- function(info_ptr) {
    .Call(`_focus_detector_candidates`, info_ptr)
}

focus_offline <- function(Y, threshold, type, family, theta0 = NULL, dim_indexes = NULL, pruning_mult = 2L, pruning_offset = 1L, side = "right") {
    .Call(`_focus_focus_offline`, Y, threshold, type, family, theta0, dim_indexes, pruning_mult, pruning_offset, side)
}

rcpp_hello_world <- function() {
    .Call(`_focus_rcpp_hello_world`)
}

