// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// detector_create
SEXP detector_create(std::string family, std::string info);
RcppExport SEXP _focus_detector_create(SEXP familySEXP, SEXP infoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< std::string >::type info(infoSEXP);
    rcpp_result_gen = Rcpp::wrap(detector_create(family, info));
    return rcpp_result_gen;
END_RCPP
}
// detector_update
void detector_update(SEXP detector_ptr, NumericVector y);
RcppExport SEXP _focus_detector_update(SEXP detector_ptrSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type detector_ptr(detector_ptrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    detector_update(detector_ptr, y);
    return R_NilValue;
END_RCPP
}
// detector_statistic
double detector_statistic(SEXP detector_ptr);
RcppExport SEXP _focus_detector_statistic(SEXP detector_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type detector_ptr(detector_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(detector_statistic(detector_ptr));
    return rcpp_result_gen;
END_RCPP
}
// detector_changepoint
List detector_changepoint(SEXP detector_ptr);
RcppExport SEXP _focus_detector_changepoint(SEXP detector_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type detector_ptr(detector_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(detector_changepoint(detector_ptr));
    return rcpp_result_gen;
END_RCPP
}
// detector_pieces_len
int detector_pieces_len(SEXP detector_ptr);
RcppExport SEXP _focus_detector_pieces_len(SEXP detector_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type detector_ptr(detector_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(detector_pieces_len(detector_ptr));
    return rcpp_result_gen;
END_RCPP
}
// detector_info_n
int detector_info_n(SEXP detector_ptr);
RcppExport SEXP _focus_detector_info_n(SEXP detector_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type detector_ptr(detector_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(detector_info_n(detector_ptr));
    return rcpp_result_gen;
END_RCPP
}
// detector_info_sn
std::vector<double> detector_info_sn(SEXP detector_ptr);
RcppExport SEXP _focus_detector_info_sn(SEXP detector_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type detector_ptr(detector_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(detector_info_sn(detector_ptr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _focus_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_focus_detector_create", (DL_FUNC) &_focus_detector_create, 2},
    {"_focus_detector_update", (DL_FUNC) &_focus_detector_update, 2},
    {"_focus_detector_statistic", (DL_FUNC) &_focus_detector_statistic, 1},
    {"_focus_detector_changepoint", (DL_FUNC) &_focus_detector_changepoint, 1},
    {"_focus_detector_pieces_len", (DL_FUNC) &_focus_detector_pieces_len, 1},
    {"_focus_detector_info_n", (DL_FUNC) &_focus_detector_info_n, 1},
    {"_focus_detector_info_sn", (DL_FUNC) &_focus_detector_info_sn, 1},
    {"_focus_rcpp_hello_world", (DL_FUNC) &_focus_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_focus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
