[metadata]
name = focus_cpt
version = 0.1.5
description = Online Changepoint Detection in Univariate and Multivariate Data Streams using FOCUS algorithms
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/gtromano/unified_focus
author = Gaetano Romano, Kes Ward, Guillem Rigaill, Vincent Runge, Paul Fearnhead, Idris A. Eckley
author_email = g.romano@lancaster.ac.uk
license = GPL-3.0-or-later
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Science/Research
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12

[options]
packages = find:
python_requires = >=3.8
install_requires =
    numpy>=1.19.0

[options.packages.find]
exclude =
    tests*
    docs*
    build*
    dist*
